-- Migration: Add Folders Table and Link Products
-- 1. Create folders table
CREATE TABLE IF NOT EXISTS folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    source_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add folder_id to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS folder_id BIGINT REFERENCES folders(id);

-- 3. (Optional) Create index for performance
CREATE INDEX IF NOT EXISTS idx_products_folder_id ON products(folder_id);
