-- Crea la tabella report_recipients
create table if not exists report_recipients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  target_email text not null,
  report_frequency text not null CHECK (report_frequency IN ('Giornaliero', 'Settimanale', 'Mensile', 'Mai')),
  target_website text
);

-- Abilita RLS (Opzionale, ma consigliato)
alter table report_recipients enable row level security;

-- Policy di lettura/scrittura aperta (o restringi come preferisci per l'app dashboard)
create policy "Enable all access for authenticated users" on report_recipients
  for all using (true) with check (true);
